name: usv
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - lightning
  - tqdm
  - scipy
  - matplotlib
  - pandas
  - ipykernel